server:
  port: 80
  session:
    timeout: 21600

spring:
    datasource:
        name: datasource
        url: jdbc:mysql://127.0.0.1:3306/record?useSSL=false
        username: root
        password: c327433910
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    typeAliasesPackage: org.uy.record.entity
    mapperLocations: classpath:mapper/*Mapper.xml
    configLocation: classpath:mybatis.xml

